version: "3"

networks:
  dbnet:

services:
  db:
    build: ./database
    image: database
    container_name: database
    ports:
      - "5432:5432"
    networks:
      - dbnet

  web:
    build: ./postgrsql
    image: postgrsql
    container_name: postgrsql
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - dbnet
    links:
      - db
    environment:
      - PORT=8000
      - LOCAL_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test_db

  

    