version: "3"

services:
  db:
    build: ./database
    image: database
    container_name: database
    ports:
      - "5432:5432"
    volumes:     
      - dbdata:/data/db

  web:
    build: ./postgrsql
    image: postgrsql
    container_name: postgrsql
    depends_on:
      - db
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      - PORT_DB=5432
      - HOST_DB=172.18.0.2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test_db

volumes:
  dbdata:

  

    